---

# This play fetch the param_projectname from Cloudforms service object when you retire a service and present it as a project_name
# To be used for deletion
# Auth: smossber@redhat.com

- name: Set the Service URL
  set_fact:
    svc_url: "/api/{{ manageiq.service }}"
    
- name: Query CloudForms for Service vars
  uri:
    url: "{{ manageiq.api_url }}/{{ svc_url }}"
    method: GET
    validate_certs: no
    headers:
       X-Auth-Token: "{{ manageiq.api_token }}"
       Content-Type: "application/json"
    body_format: json
    return_content: yes
  register: service_output
  
- name: Set the projectname
  set_fact:
    project_name: "{{ service_output.json.options.dialog.dialog_param_projectname }}"

- name: delete  {{ project_name }}
  command: oc delete project {{ project_name }}
