---

- name: create oc {{ projectname }}
  command: oadm new-project {{ projectname }} 

- name: create admin rights for {{ username }}
  command: oc policy add-role-to-user admin {{ username }} -n {{ projectname }}
