---
- name: Check for project before running play
  command: oc get projects | grep {{ projectname }}
  register: command
  ignore_errors: true

- name: The project exists, can not create new project with the {{ projectname }}
  fail: msg="Not able to create project due to project already exists"
  when: when: "'Error' in command.stderr"

- name: create oc {{ projectname }}-dev
  command: oadm new-project {{ projectname }}-dev --node-selector="site=dev"

- name: create oc {{ projectname }}-test
  command: oadm new-project {{ projectname }}-test --node-selector="site=test"

- name: create oc {{ projectname }}-prod
  command: oadm new-project {{ projectname }}-prod --node-selector="site=prod"

- name: create oc {{ projectname }}-jenkins
  command: oadm new-project {{ projectname }}-jenkins --node-selector="site=dev"

- name: Add user as admin for {{ projectname }}-dev
  command: oc policy add-role-to-user admin {{ username }} -n {{ projectname }}-dev

- name: Add user as admin for {{ projectname }}-test
  command: oc policy add-role-to-user admin {{ username }} -n {{ projectname }}-test

- name: Add user as admin for {{ projectname }}-prod
  command: oc policy add-role-to-user admin {{ username }} -n {{ projectname }}-prod

- name: Add user as admin for {{ projectname }}-jenkins
  command: oc policy add-role-to-user admin {{ username }} -n {{ projectname }}-jenkins

- name: Add project pipeline to {{ projectname }}-dev
  command: oc policy add-role-to-group system:image-puller system:serviceaccount:{{ projectname }}-prod -n {{ projectname }}-dev

- name: Add project pipeline to {{ projectname }}-dev
  command: oc policy add-role-to-group system:image-puller system:serviceaccount:{{ projectname }}-test -n {{ projectname }}-dev

- name: Add jenkins to project {{ projectname }}-jenkins
  command: oc new-app jenkins-persistent -n {{ projectname }}-jenkins

- name: Add Jenkins role to {{ projectname }}-dev
  command: oc policy add-role-to-user edit system:serviceaccount:{{ projectname }}-jenkins:jenkins -n {{ projectname }}-dev

- name: Add Jenkins role to {{ projectname }}-test
  command: oc policy add-role-to-user edit system:serviceaccount:{{ projectname }}-jenkins:jenkins -n {{ projectname }}-test

- name: Add Jenkins role to {{ projectname }}-prod
  command: oc policy add-role-to-user edit system:serviceaccount:{{ projectname }}-jenkins:jenkins -n {{ projectname }}-prod
